{{- if .Values.rabbitmq.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pitch.fullname" . }}-rabbitmq
  labels:
    {{- include "pitch.labels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
spec:
  ports:
  - port: {{ .Values.rabbitmq.service.ports.amqp }}
    name: amqp
  - port: {{ .Values.rabbitmq.service.ports.management }}
    name: management
  - port: {{ .Values.rabbitmq.service.ports.metrics }}
    name: metrics
  clusterIP: None
  selector:
    {{- include "pitch.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "pitch.fullname" . }}-rabbitmq
  labels:
    {{- include "pitch.labels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
spec:
  serviceName: {{ include "pitch.fullname" . }}-rabbitmq
  replicas: 1
  selector:
    matchLabels:
      {{- include "pitch.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: rabbitmq
  template:
    metadata:
      labels:
        {{- include "pitch.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: {{ .Values.rabbitmq.image.registry }}/{{ .Values.rabbitmq.image.repository }}:{{ .Values.rabbitmq.image.tag }}
        env:
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.existingSecret | default (printf "%s-secrets" (include "pitch.fullname" .)) }}
              key: rabbitmq-user
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.existingSecret | default (printf "%s-secrets" (include "pitch.fullname" .)) }}
              key: rabbitmq-password
        - name: RABBITMQ_DEFAULT_VHOST
          value: {{ .Values.rabbitmq.auth.vhost | quote }}
        ports:
        - containerPort: {{ .Values.rabbitmq.service.ports.amqp }}
          name: amqp
        - containerPort: {{ .Values.rabbitmq.service.ports.management }}
          name: management
        - containerPort: {{ .Values.rabbitmq.service.ports.metrics }}
          name: metrics
        livenessProbe:
          tcpSocket:
            port: 5672
          initialDelaySeconds: 60
          periodSeconds: 15
          failureThreshold: 6
        readinessProbe:
          tcpSocket:
            port: 5672
          initialDelaySeconds: 20
          periodSeconds: 10
        volumeMounts:
        - name: data
          mountPath: /var/lib/rabbitmq
        resources:
          {{- toYaml .Values.rabbitmq.resources | nindent 12 }}
      {{- if not .Values.rabbitmq.persistence.enabled }}
      volumes:
      - name: data
        emptyDir: {}
      {{- end }}
  {{- if .Values.rabbitmq.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      {{- if .Values.global.storageClass }}
      storageClassName: {{ .Values.global.storageClass | quote }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.rabbitmq.persistence.size }}
  {{- end }}
{{- end }}
